name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Change directory to 2022
      run: cd 2022/
    - name: Cargo run test
      run: cargo test --release
    - name: Cargo run benchmark
      run: cargo bench
